/*
 Hyphenator 3.1.0 - client side hyphenation for webbrowsers
 Copyright (C) 2010  Mathias Nater, Zürich (mathias at mnn dot ch)
 Project and Source hosted on http://code.google.com/p/hyphenator/

 This JavaScript code is free software: you can redistribute
 it and/or modify it under the terms of the GNU Lesser
 General Public License (GNU LGPL) as published by the Free Software
 Foundation, either version 3 of the License, or (at your option)
 any later version.  The code is distributed WITHOUT ANY WARRANTY;
 without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU GPL for more details.

 As additional permission under GNU GPL version 3 section 7, you
 may distribute non-source (e.g., minimized or compacted) forms of
 that code without the copy of the GNU GPL normally required by
 section 4, provided you include this license notice and a URL
 through which recipients can access the Corresponding Source.
*/
var Hyphenator=function(g){var r={no:"Hyphenator-no.js"},ka=function(){var b,a="";for(b in r)if(r.hasOwnProperty(b))a+=b+", ";return a=a.substring(0,a.length-2)}(),J={be:"\u041c\u043e\u0432\u0430 \u0433\u044d\u0442\u0430\u0433\u0430 \u0441\u0430\u0439\u0442\u0430 \u043d\u0435 \u043c\u043e\u0436\u0430 \u0431\u044b\u0446\u044c \u0432\u044b\u0437\u043d\u0430\u0447\u0430\u043d\u044b \u0430\u045e\u0442\u0430\u043c\u0430\u0442\u044b\u0447\u043d\u0430. \u041a\u0430\u043b\u0456 \u043b\u0430\u0441\u043a\u0430 \u043f\u0430\u043a\u0430\u0436\u044b\u0446\u0435 \u043c\u043e\u0432\u0443:",
cs:"Jazyk t\u00e9to internetov\u00e9 str\u00e1nky nebyl automaticky rozpozn\u00e1n. Ur\u010dete pros\u00edm jej\u00ed jazyk:",da:"Denne websides sprog kunne ikke bestemmes. Angiv venligst sprog:",de:"Die Sprache dieser Webseite konnte nicht automatisch bestimmt werden. Bitte Sprache angeben:",en:"The language of this website could not be determined automatically. Please indicate the main language:",es:"El idioma del sitio no pudo determinarse autom%E1ticamente. Por favor, indique el idioma principal:",
fi:"Sivun kielt%E4 ei tunnistettu automaattisesti. M%E4%E4rit%E4 sivun p%E4%E4kieli:",fr:"La langue de ce site n%u2019a pas pu %EAtre d%E9termin%E9e automatiquement. Veuillez indiquer une langue, s.v.p.%A0:",hu:"A weboldal nyelv\u00e9t nem siker\u00fclt automatikusan meg\u00e1llap\u00edtani. K\u00e9rem adja meg a nyelvet:",hy:"\u0549\u0570\u0561\u057b\u0578\u0572\u057e\u0565\u0581 \u0570\u0561\u0575\u057f\u0576\u0561\u0562\u0565\u0580\u0565\u056c \u0561\u0575\u057d \u056f\u0561\u0575\u0584\u056b \u056c\u0565\u0566\u0578\u0582\u0576\u0589 \u053d\u0576\u0564\u0580\u0578\u0582\u0574 \u0565\u0576\u0584 \u0576\u0577\u0565\u0584 \u0570\u056b\u0574\u0576\u0561\u056f\u0561\u0576 \u056c\u0565\u0566\u0578\u0582\u0576\u055d",
it:"Lingua del sito sconosciuta. Indicare una lingua, per favore:",kn:"\u0c9c\u0cbe\u0cb2 \u0ca4\u0cbe\u0ca3\u0ca6 \u0cad\u0cbe\u0cb7\u0cc6\u0caf\u0ca8\u0ccd\u0ca8\u0cc1 \u0ca8\u0cbf\u0cb0\u0ccd\u0ca7\u0cb0\u0cbf\u0cb8\u0cb2\u0cc1 \u0cb8\u0cbe\u0ca7\u0ccd\u0caf\u0cb5\u0cbe\u0c97\u0cc1\u0ca4\u0ccd\u0ca4\u0cbf\u0cb2\u0ccd\u0cb2. \u0ca6\u0caf\u0cb5\u0cbf\u0c9f\u0ccd\u0c9f\u0cc1 \u0cae\u0cc1\u0c96\u0ccd\u0caf \u0cad\u0cbe\u0cb7\u0cc6\u0caf\u0ca8\u0ccd\u0ca8\u0cc1 \u0cb8\u0cc2\u0c9a\u0cbf\u0cb8\u0cbf:",
lt:"Nepavyko automati\u0161kai nustatyti \u0161ios svetain\u0117s kalbos. Pra\u0161ome \u012fvesti kalb\u0105:",ml:"\u0d08 \u0d35\u0d46%u0D2C%u0D4D%u200C\u0d38\u0d48\u0d31\u0d4d\u0d31\u0d3f\u0d28\u0d4d\u0d31\u0d46 \u0d2d\u0d3e\u0d37 \u0d15\u0d23\u0d4d\u0d1f\u0d41\u0d2a\u0d3f\u0d1f\u0d3f\u0d2f\u0d4d\u0d15\u0d4d\u0d15\u0d3e%u0D28%u0D4D%u200D \u0d15\u0d34\u0d3f\u0d1e\u0d4d\u0d1e\u0d3f\u0d32\u0d4d\u0d32. \u0d2d\u0d3e\u0d37 \u0d0f\u0d24\u0d3e\u0d23\u0d46\u0d28\u0d4d\u0d28\u0d41 \u0d24\u0d3f\u0d30\u0d1e\u0d4d\u0d1e\u0d46\u0d1f\u0d41\u0d15\u0d4d\u0d15\u0d41\u0d15:",
nl:"De taal van deze website kan niet automatisch worden bepaald. Geef de hoofdtaal op:",pt:"A l\u00edngua deste site n\u00e3o p\u00f4de ser determinada automaticamente. Por favor indique a l\u00edngua principal:",ru:"\u042f\u0437\u044b\u043a \u044d\u0442\u043e\u0433\u043e \u0441\u0430\u0439\u0442\u0430 \u043d\u0435 \u043c\u043e\u0436\u0435\u0442 \u0431\u044b\u0442\u044c \u043e\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438. \u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430 \u0443\u043a\u0430\u0436\u0438\u0442\u0435 \u044f\u0437\u044b\u043a:",
sl:"Jezika te spletne strani ni bilo mogo\u010de samodejno dolo\u010diti. Prosim navedite jezik:",sv:"Spr%E5ket p%E5 den h%E4r webbplatsen kunde inte avg%F6ras automatiskt. V%E4nligen ange:",tr:"Bu web sitesinin dilini otomatik olarak tespit edilememi\u015ftir. L\u00fctfen ana dili g\u00f6sterir:",uk:"\u041c\u043e\u0432\u0430 \u0446\u044c\u043e\u0433\u043e \u0432\u0435\u0431-\u0441\u0430\u0439\u0442\u0443 \u043d\u0435 \u043c\u043e\u0436\u0435 \u0431\u0443\u0442\u0438 \u0432\u0438\u0437\u043d\u0430\u0447\u0435\u043d\u0430 \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u043d\u043e. \u0411\u0443\u0434\u044c \u043b\u0430\u0441\u043a\u0430, \u0432\u043a\u0430\u0436\u0456\u0442\u044c \u0433\u043e\u043b\u043e\u0432\u043d\u0443 \u043c\u043e\u0432\u0443:"},
X=function(){for(var b=document.getElementsByTagName("script"),a=0,c,d;c=b[a++];)if(c.src){d=c.src;c=d.indexOf("Hyphenator.js");if(c!==-1)return d.substring(0,c)}return"http://hyphenator.googlecode.com/svn/trunk/"}(),la=function(){var b=false;if(g.location.href.indexOf(X)!==-1)b=true;return b}(),B=false,w=0,l=g,x=false,Y={script:true,code:true,pre:true,img:true,br:true,samp:true,kbd:true,"var":true,abbr:true,acronym:true,sub:true,sup:true,button:true,option:true,label:true,textarea:true,input:true},
E=true,K="local",s,L=false,Z=true,$=false,M="hyphenate",F="donthyphenate",C=6,G=1,y=function(){var b=null,a=false,c=document.getElementsByTagName("script"),d,e;d=0;for(e=c.length;d<e;d++){if(c[d].getAttribute("src"))b=c[d].getAttribute("src");if(b)if(b.indexOf("Hyphenator.js?bm=true")!==-1)a=true}return a}(),m=null,z=[],n={},q={},u=0,aa=RegExp("((\\w*://)?((\\w*:)?(\\w*)@)?((([\\d]{1,3}\\.){3}([\\d]{1,3}))|((www\\.|[a-zA-Z]\\.)?[a-zA-Z0-9\\-\\.]+\\.([a-z]{2,4})))(:\\d*)?(/[\\w#!:\\.?\\+=&%@!\\-]*)*)|([\\w-\\.]+@[\\w\\.]+)",
"i"),N=function(){var b,a=navigator.userAgent.toLowerCase();b=String.fromCharCode(8203);if(a.indexOf("msie 6")!==-1)b="";if(a.indexOf("opera")!==-1&&a.indexOf("version/10.00")!==-1)b="";return b}(),O=function(b,a){a=a||l;if(document.createElementNS)return a.document.createElementNS("http://www.w3.org/1999/xhtml",b);else if(document.createElement)return a.document.createElement(b)},ba=function(){},v=function(b){g.alert("Hyphenator.js says:\n\nAn Error ocurred:\n"+b.message)},ca=function(){var b,a=
[],c,d;if(document.getElementsByClassName)a=l.document.getElementsByClassName(M);else{b=l.document.getElementsByTagName("*");d=b.length;for(c=0;c<d;c++)b[c].className.indexOf(M)!==-1&&b[c].className.indexOf(F)===-1&&a.push(b[c])}return a},P="hidden",t=String.fromCharCode(173),da=N,ea=true,Q=function(){var b={},a="HyphenatorExpando_"+Math.random(),c=0;return{getDataForElem:function(d){return b[d[a].id]},setDataForElem:function(d,e){var f;if(d[a]&&d[a].id!=="")f=d[a].id;else{f=c++;d[a]={id:f}}b[f]=
e},appendDataForElem:function(d,e){for(var f in e)if(e.hasOwnProperty(f))b[d[a].id][f]=e[f]},delDataOfElem:function(d){delete b[d[a]]}}}(),ma=function(b,a){function c(k){l=k||g;if(!h[l.location.href]&&(!B||l!=g.parent)){B=true;a();h[l.location.href]=true}}function d(){try{document.documentElement.doScroll("left")}catch(k){setTimeout(d,1);return}c(g)}function e(){var k,o,p=g.frames.length;if(x&&p>0){for(k=0;k<p;k++){o=undefined;try{o=g.frames[k].document.toString()}catch(D){o=undefined}o&&c(g.frames[k])}l=
g;a();h[g.location.href]=true}else c(g)}var f=function(){},i,h={};if(B&&!h[b.location.href]){a();h[b.location.href]=true}else{if(document.addEventListener)f=function(){document.removeEventListener("DOMContentLoaded",f,false);x&&g.frames.length>0||c(g)};else if(document.attachEvent)f=function(){if(document.readyState==="complete"){document.detachEvent("onreadystatechange",f);x&&g.frames.length>0||c(g)}};if(document.addEventListener){document.addEventListener("DOMContentLoaded",f,false);g.addEventListener("load",
e,false)}else if(document.attachEvent){document.attachEvent("onreadystatechange",f);g.attachEvent("onload",e);i=false;try{i=g.frameElement===null}catch(j){}document.documentElement.doScroll&&i&&d()}}},R=function(b,a){if(b.getAttribute("lang"))return b.getAttribute("lang").toLowerCase();try{if(b.getAttribute("xml:lang"))return b.getAttribute("xml:lang").toLowerCase()}catch(c){}if(b.tagName!=="HTML")return R(b.parentNode,true);if(a)return m;return null},fa=function(b){b=b||l;var a=b.document.getElementsByTagName("html")[0];
b=b.document.getElementsByTagName("meta");m=R(a,false);if(!m)for(a=0;a<b.length;a++){if(b[a].getAttribute("http-equiv")&&b[a].getAttribute("http-equiv").toLowerCase()==="content-language")m=b[a].getAttribute("content").toLowerCase();if(b[a].getAttribute("name")&&b[a].getAttribute("name").toLowerCase()==="dc.language")m=b[a].getAttribute("content").toLowerCase();if(b[a].getAttribute("name")&&b[a].getAttribute("name").toLowerCase()==="language")m=b[a].getAttribute("content").toLowerCase()}!m&&x&&l!=
g.parent&&fa(g.parent);if(!m){b=navigator.language?navigator.language:navigator.userLanguage;b=b.substring(0,2);a=J.hasOwnProperty(b)?J[b]:J.en;a+=" (ISO 639-1)\n\n"+ka;m=g.prompt(unescape(a),b).toLowerCase()}if(!r.hasOwnProperty(m))if(r.hasOwnProperty(m.split("-")[0]))m=m.split("-")[0];else{a=Error('The language "'+m+'" is not yet supported.');throw a;}},na=function(){var b,a,c=0,d=function(e,f,i){var h=0,j={};if(f&&P==="hidden"){j.hasOwnStyle=e.getAttribute("style")?true:false;j.isHidden=true;e.style.visibility=
"hidden"}j.language=e.lang&&typeof e.lang==="string"?e.lang.toLowerCase():i?i.toLowerCase():R(e,true);i=j.language;if(r[i])q[i]=true;else if(r.hasOwnProperty(i.split("-")[0])){i=i.split("-")[0];j.language=i}else y||v(Error("Language "+i+" is not yet supported."));Q.setDataForElem(e,j);for(z.push(e);f=e.childNodes[h++];)f.nodeType===1&&!Y[f.nodeName.toLowerCase()]&&f.className.indexOf(F)===-1&&!(f in b)&&d(f,false,i)};if(y){b=l.document.getElementsByTagName("body")[0];d(b,false,m)}else for(b=ca();a=
b[c++];)d(a,true,"");if(Hyphenator.languages.hasOwnProperty(m))Hyphenator.languages[m].prepared||(q[m]=true);else q[m]=true;z.length>0&&Q.appendDataForElem(z[z.length-1],{isLast:true})},S=function(b){b=b.split(", ");var a={},c,d,e;c=0;for(d=b.length;c<d;c++){e=b[c].replace(/-/g,"");a.hasOwnProperty(e)||(a[e]=b[c])}return a},oa=function(b){var a,c;if(r[b]&&!Hyphenator.languages[b]){a=X+"patterns/"+r[b];if(la&&!y){c=null;if(typeof XMLHttpRequest!=="undefined")c=new XMLHttpRequest;if(!c)try{c=new ActiveXObject("Msxml2.XMLHTTP")}catch(d){c=
null}if(c){c.open("HEAD",a,false);c.setRequestHeader("Cache-Control","no-cache");c.send(null);if(c.status===404){v(Error("Could not load\n"+a));delete q[b];return}}}if(O){b=g.document.getElementsByTagName("head").item(0);c=O("script",g);c.src=a;c.type="text/javascript";b.appendChild(c)}}},T=function(b){var a=Hyphenator.languages[b],c;if(!a.prepared){if(E){a.cache={};a.cache=a.cache}if(L)a.redPatSet={};if(a.hasOwnProperty("exceptions")){Hyphenator.addExceptions(b,a.exceptions);delete a.exceptions}if(n.hasOwnProperty("global"))if(n.hasOwnProperty(b))n[b]+=
", "+n.global;else n[b]=n.global;if(n.hasOwnProperty(b)){a.exceptions=S(n[b]);delete n[b]}else a.exceptions={};var d,e,f,i,h={};f=Hyphenator.languages[b].patterns;for(c in f)if(f.hasOwnProperty(c)){c=parseInt(c,10);d=0;for(e=c;d=f[c].substring(d,e);){i=d.replace(/\d/g,"");h[i]=d;d=e;e+=c}}Hyphenator.languages[b].patterns=h;Hyphenator.languages[b].patternsConverted=true;c="[\\w"+a.specialChars+"@"+String.fromCharCode(173)+"-]{"+C+",}";a.genRegExp=RegExp("((\\w*://)?((\\w*:)?(\\w*)@)?((([\\d]{1,3}\\.){3}([\\d]{1,3}))|((www\\.|[a-zA-Z]\\.)?[a-zA-Z0-9\\-\\.]+\\.([a-z]{2,4})))(:\\d*)?(/[\\w#!:\\.?\\+=&%@!\\-]*)*)|([\\w-\\.]+@[\\w\\.]+)|("+
c+")","gi");a.prepared=true}if(s)try{s.setItem("Hyphenator_"+b,g.JSON.stringify(a))}catch(j){}},pa=function(b){var a,c=0,d,e,f;if(Z){u=1;for(a in q)if(q.hasOwnProperty(a)){++c;if(s)if(s.getItem("Hyphenator_"+a)){Hyphenator.languages[a]=g.JSON.parse(s.getItem("Hyphenator_"+a));if(n.hasOwnProperty("global")){e=S(n.global);for(f in e)if(e.hasOwnProperty(f))Hyphenator.languages[a].exceptions[f]=e[f]}if(n.hasOwnProperty(a)){e=S(n[a]);for(f in e)if(e.hasOwnProperty(f))Hyphenator.languages[a].exceptions[f]=
e[f];delete n[a]}e="[\\w"+Hyphenator.languages[a].specialChars+"@"+String.fromCharCode(173)+"-]{"+C+",}";Hyphenator.languages[a].genRegExp=RegExp("((\\w*://)?((\\w*:)?(\\w*)@)?((([\\d]{1,3}\\.){3}([\\d]{1,3}))|((www\\.|[a-zA-Z]\\.)?[a-zA-Z0-9\\-\\.]+\\.([a-z]{2,4})))(:\\d*)?(/[\\w#!:\\.?\\+=&%@!\\-]*)*)|([\\w-\\.]+@[\\w\\.]+)|("+e+")","gi");delete q[a];--c;continue}oa(a)}if(c===0){u=2;b()}else d=g.setInterval(function(){var i=false,h;for(h in q)if(q.hasOwnProperty(h))if(Hyphenator.languages[h]){i=
true;delete q[h];T(h)}else{i=false;break}if(i){g.clearInterval(d);u=2;b()}},100)}else{for(a in Hyphenator.languages)Hyphenator.languages.hasOwnProperty(a)&&T(a);u=2;b()}},H=function(b){var a,c,d,e;if(a=l.document.getElementById("HyphenatorToggleBox"))a.firstChild.data=b?"Hy-phe-na-ti-on":"Hyphenation";else{b=l.document.getElementsByTagName("body")[0];a=O("div",l);c=l.document.createAttribute("id");c.nodeValue="HyphenatorToggleBox";e=l.document.createAttribute("class");e.nodeValue=F;d=l.document.createTextNode("Hy-phe-na-ti-on");
a.appendChild(d);a.setAttributeNode(c);a.setAttributeNode(e);a.onclick=Hyphenator.toggleHyphenation;a.style.position="absolute";a.style.top="0px";a.style.right="0px";a.style.margin="0";a.style.backgroundColor="#AAAAAA";a.style.color="#FFFFFF";a.style.font="6pt Arial";a.style.letterSpacing="0.2em";a.style.padding="3px";a.style.cursor="pointer";a.style.WebkitBorderBottomLeftRadius="4px";a.style.MozBorderRadiusBottomleft="4px";b.appendChild(a)}},W=function(b,a){var c=Hyphenator.languages[b],d,e,f,i,
h,j,k,o,p=false,D,A,U,ga,ha,V;if(a==="")return"";if(a.indexOf(t)!==-1)return a;if(E&&c.cache.hasOwnProperty(a))return c.cache[a];if(c.exceptions.hasOwnProperty(a))return c.exceptions[a].replace(/-/g,t);if(a.indexOf("-")!==-1){c=a.split("-");d=0;for(e=c.length;d<e;d++)c[d]=W(b,c[d]);return c.join("-")}f="_"+a+"_";i=f.length;e=f.split("");f=a.indexOf("'")!==-1?f.toLowerCase().replace("'","\u2019"):f.toLowerCase();h=[];ha={"0":0,"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9};ga=i-c.shortestPattern;
for(j=0;j<=ga;j++){k=Math.min(i-j,c.longestPattern);for(o=c.shortestPattern;o<=k;o++)if(c.patterns.hasOwnProperty(D=f.substring(j,j+o))){p=c.patterns[D];if(L)c.redPatSet[D]=p;if(typeof p==="string"){U=0;V=[];for(d=0;d<p.length;d++)if(A=ha[p.charAt(d)]){V.push(d-U,A);U++}p=c.patterns[D]=V}for(d=0;d<p.length;d++){A=j-1+p[d];if(!h[A]||h[A]<p[d+1])h[A]=p[d+1];d++}}}f=0;for(d=c.leftmin;d<=a.length-c.rightmin;d++)if(h[d]&1){e.splice(d+f+1,0,t);f++}d=e.slice(1,-1).join("");if(E)c.cache[a]=d;return d},ia=
function(b){return b.replace(/([:\/\.\?#&_,;!@]+)/gi,"$&"+da)},qa=function(b){var a=Q.getDataForElem(b),c=a.language,d,e,f,i=function(h){var j,k;switch(t){case "|":j="\\|";break;case "+":j="\\+";break;case "*":j="\\*";break;default:j=t}if(G>=2){k=h.split(" ");k[1]=k[1].replace(RegExp(j,"g"),"");k[1]=k[1].replace(RegExp(N,"g"),"");k=k.join(" ")}if(G===3)k=k.replace(/[ ]+/g,String.fromCharCode(160));return k};if(Hyphenator.languages.hasOwnProperty(c)){d=function(h){return aa.test(h)?ia(h):W(c,h)};for(f=
0;e=b.childNodes[f++];)if(e.nodeType===3&&e.data.length>=C){e.data=e.data.replace(Hyphenator.languages[c].genRegExp,d);if(G!==1)e.data=e.data.replace(/[\S]+ [\S]+$/,i)}}if(a.isHidden&&P==="hidden"){b.style.visibility="visible";if(a.hasOwnStyle)if(b.style.removeProperty)b.style.removeProperty("visibility");else b.style.removeAttribute&&b.style.removeAttribute("visibility");else{b.setAttribute("style","");b.removeAttribute("style")}}if(a.isLast){u=3;w--;if(w>-1E3&&w<=0){w=-2E3;ba()}}},I=function(b){var a,
c=0,d;switch(t){case "|":a="\\|";break;case "+":a="\\+";break;case "*":a="\\*";break;default:a=t}for(;d=b.childNodes[c++];)if(d.nodeType===3){d.data=d.data.replace(RegExp(a,"g"),"");d.data=d.data.replace(RegExp(N,"g"),"")}else d.nodeType===1&&I(d)},ja=function(){function b(d,e){return function(){return d(e)}}for(var a=0,c;c=z[a++];)c.ownerDocument.location.href===l.location.href&&g.setTimeout(b(qa,c),0)},ra=function(){var b=l.document.getElementsByTagName("body")[0],a,c,d,e,f,i=function(h){h=h||g.event;
h=h.target||h.srcElement;var j=h.ownerDocument,k=j.getElementsByTagName("body")[0],o="defaultView"in j?j.defaultView:j.parentWindow;if(!(h.tagName&&Y[h.tagName.toLowerCase()])){a=j.createElement("div");a.style.overflow="hidden";a.style.position="absolute";a.style.top="-5000px";a.style.height="1px";k.appendChild(a);if(g.getSelection){c=o.getSelection();d=c.getRangeAt(0);a.appendChild(d.cloneContents());I(a);c.selectAllChildren(a);f=function(){a.parentNode.removeChild(a);o.getSelection().setBaseAndExtent&&
c.setBaseAndExtent(d.startContainer,d.startOffset,d.endContainer,d.endOffset)}}else{c=o.document.selection;d=c.createRange();a.innerHTML=d.htmlText;I(a);e=k.createTextRange();e.moveToElementText(a);e.select();f=function(){a.parentNode.removeChild(a);d.text!==""&&d.select()}}g.setTimeout(f,0)}};if(b)g.addEventListener?b.addEventListener("copy",i,false):b.attachEvent("oncopy",i)};return{version:"3.1.0",languages:{},config:function(b){var a=function(d,e){if(typeof b[d]===e)return true;else{v(Error("Config onError: "+
d+" must be of type "+e));return false}},c;for(c in b)if(b.hasOwnProperty(c))switch(c){case "classname":if(a("classname","string"))M=b[c];break;case "donthyphenateclassname":if(a("donthyphenateclassname","string"))F=b[c];break;case "minwordlength":if(a("minwordlength","number"))C=b[c];break;case "hyphenchar":if(a("hyphenchar","string")){if(b.hyphenchar==="&shy;")b.hyphenchar=String.fromCharCode(173);t=b[c]}break;case "urlhyphenchar":if(b.hasOwnProperty("urlhyphenchar"))if(a("urlhyphenchar","string"))da=
b[c];break;case "togglebox":if(a("togglebox","function"))H=b[c];break;case "displaytogglebox":if(a("displaytogglebox","boolean"))$=b[c];break;case "remoteloading":if(a("remoteloading","boolean"))Z=b[c];break;case "enablecache":if(a("enablecache","boolean"))E=b[c];break;case "enablereducedpatternset":if(a("enablereducedpatternset","boolean"))L=b[c];break;case "onhyphenationdonecallback":if(a("onhyphenationdonecallback","function"))ba=b[c];break;case "onerrorhandler":if(a("onerrorhandler","function"))v=
b[c];break;case "intermediatestate":if(a("intermediatestate","string"))P=b[c];break;case "selectorfunction":if(a("selectorfunction","function"))ca=b[c];break;case "safecopy":if(a("safecopy","boolean"))ea=b[c];break;case "doframes":if(a("doframes","boolean"))x=b[c];break;case "storagetype":if(a("storagetype","string"))K=b[c];break;case "orphancontrol":if(a("orphancontrol","number"))G=b[c];break;default:v(Error("Hyphenator.config: property "+c+" not known."))}},run:function(){w=0;var b=function(){try{if(!(l.document.getElementsByTagName("frameset").length>
0)){w++;fa(undefined);na();pa(ja);$&&H(true);ea&&ra()}}catch(i){v(i)}},a,c,d=g.frames.length;try{if(K!=="none"&&typeof g.localStorage!=="undefined"&&typeof g.sessionStorage!=="undefined"&&typeof g.JSON.stringify!=="undefined"&&typeof g.JSON.parse!=="undefined")switch(K){case "session":s=g.sessionStorage;break;case "local":s=g.localStorage;break;default:s=undefined}}catch(e){}!B&&!y&&ma(g,b);if(y||B){if(x&&d>0)for(a=0;a<d;a++){c=undefined;try{c=g.frames[a].document.toString()}catch(f){c=undefined}if(c){l=
g.frames[a];b()}}l=g;b()}},addExceptions:function(b,a){if(b==="")b="global";if(n.hasOwnProperty(b))n[b]+=", "+a;else n[b]=a},hyphenate:function(b,a){var c,d,e;if(Hyphenator.languages.hasOwnProperty(a)){Hyphenator.languages[a].prepared||T(a);c=function(f){return aa.test(f)?ia(f):W(a,f)};if(typeof b==="string"||b.constructor===String)return b.replace(Hyphenator.languages[a].genRegExp,c);else if(typeof b==="object")for(e=0;d=b.childNodes[e++];)if(d.nodeType===3&&d.data.length>=C)d.data=d.data.replace(Hyphenator.languages[a].genRegExp,
c);else if(d.nodeType===1)d.lang!==""?Hyphenator.hyphenate(d,d.lang):Hyphenator.hyphenate(d,a)}else v(Error('Language "'+a+'" is not loaded.'))},getRedPatternSet:function(b){return Hyphenator.languages[b].redPatSet},isBookmarklet:function(){return y},getConfigFromURI:function(){var b=null,a={},c=document.getElementsByTagName("script"),d,e,f;d=0;for(e=c.length;d<e;d++){if(c[d].getAttribute("src"))b=c[d].getAttribute("src");if(b){f=b.indexOf("Hyphenator.js?");if(f!==-1){c=b.substring(f+14).split("&");
for(b=0;b<c.length;b++){d=c[b].split("=");if(d[0]!=="bm")a[d[0]]=d[1]==="true"?true:d[1]==="false"?false:isFinite(d[1])?parseInt(d[1],10):d[0]==="onhyphenationdonecallback"?new Function("",d[1]):d[1]}break}}}return a},toggleHyphenation:function(){switch(u){case 3:for(var b=0,a;a=z[b++];)I(a);u=4;H(false);break;case 4:ja();H(true)}}}}(window);Hyphenator.languages=Hyphenator.languages;Hyphenator.config=Hyphenator.config;Hyphenator.run=Hyphenator.run;Hyphenator.addExceptions=Hyphenator.addExceptions;
Hyphenator.hyphenate=Hyphenator.hyphenate;Hyphenator.getRedPatternSet=Hyphenator.getRedPatternSet;Hyphenator.isBookmarklet=Hyphenator.isBookmarklet;Hyphenator.getConfigFromURI=Hyphenator.getConfigFromURI;Hyphenator.toggleHyphenation=Hyphenator.toggleHyphenation;window.Hyphenator=Hyphenator;Hyphenator.config({remoteloading:false});
